// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAFZWFulcZCIgbSwbxgWwhdHvUB6vQ_tg',
    appId: '1:961340816883:web:8429ac3ec13030d914e686',
    messagingSenderId: '961340816883',
    projectId: 'login-b120c',
    authDomain: 'login-b120c.firebaseapp.com',
    storageBucket: 'login-b120c.appspot.com',
    measurementId: 'G-QTR6DTT9T3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAofBqUY5K9b1quRJZ4xvVYLBNG6iKqrcg',
    appId: '1:961340816883:android:bf24694a17b8995a14e686',
    messagingSenderId: '961340816883',
    projectId: 'login-b120c',
    storageBucket: 'login-b120c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4XCYZsdpIXHqQIiOt8gOWWz3LkI4E2Ww',
    appId: '1:961340816883:ios:bdd9d06551fedef714e686',
    messagingSenderId: '961340816883',
    projectId: 'login-b120c',
    storageBucket: 'login-b120c.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4XCYZsdpIXHqQIiOt8gOWWz3LkI4E2Ww',
    appId: '1:961340816883:ios:bdd9d06551fedef714e686',
    messagingSenderId: '961340816883',
    projectId: 'login-b120c',
    storageBucket: 'login-b120c.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAFZWFulcZCIgbSwbxgWwhdHvUB6vQ_tg',
    appId: '1:961340816883:web:a9a21507aaa7bbe914e686',
    messagingSenderId: '961340816883',
    projectId: 'login-b120c',
    authDomain: 'login-b120c.firebaseapp.com',
    storageBucket: 'login-b120c.appspot.com',
    measurementId: 'G-3KKD918233',
  );
}
